// Создание таблицы счетов
DROP TABLE IF EXISTS Accounts;
CREATE TABLE Accounts (`Счет` VARCHAR(10) NOT NULL PRIMARY KEY, `Наименование` VARCHAR(63) NOT NULL, `Дебет` DECIMAL(12,2) NOT NULL DEFAULT '0', `Кредит` DECIMAL(12,2) NOT NULL DEFAULT '0', `АП` ENUM('','А','П') NOT NULL, `Количество` INT NOT NULL DEFAULT '0', `Цена_Розн` DECIMAL(12,2) NOT NULL, `Код` VARCHAR(255) NOT NULL, `ИНН` VARCHAR(12) NOT NULL);
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('01', 'Основные средства', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('02', 'Амортизация основных средств', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('03', 'Доходные вложения в материальные ценности', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('04', 'Нематериальные активы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('05', 'Амортизация нематериальных активов', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('07', 'Оборудование к установке', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('08', 'Вложения во внеоборотные активы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('09', 'Отложенные налоговые активы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('10', 'Материалы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('11', 'Животные на выращивании и откорме', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('14', 'Резервы под снижение стоимости материальных ценностей', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('15', 'Заготовление и приобретение материальных ценностей', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('16', 'Отклонение в стоимости материальных ценностей', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('19', 'Налог на добавленную стоимость по приобретенным ценностям', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('20', 'Основное производство', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('21', 'Полуфабрикаты собственного производства', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('23', 'Вспомогательные производства', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('25', 'Общепроизводственные расходы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('26', 'Общехозяйственные расходы', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('28', 'Брак в производстве', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('29', 'Обслуживающие производства и хозяйства', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('40', 'Выпуск продукции (работ, услуг)', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('41', 'Товары', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('42', 'Торговая наценка', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('43', 'Готовая продукция', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('44', 'Расходы на продажу', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('45', 'Товары отгруженные', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('46', 'Выполненные этапы по незавершенным работам', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('50', 'Касса', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('51', 'Расчетные счета', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('55', 'Специальные счета в банках', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('57', 'Переводы в пути', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('58', 'Финансовые вложения', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('59', 'Резервы под обесценение финансовых вложений', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('60', 'Расчеты с поставщиками и подрядчиками', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('62', 'Расчеты с покупателями и заказчиками', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('63', 'Резервы по сомнительным долгам', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('66', 'Расчеты по краткосрочным кредитам и займам', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('67', 'Расчеты по долгосрочным кредитам и займам', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('68', 'Расчеты по налогам и сборам', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('69', 'Расчеты по социальному страхованию и обеспечению', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('70', 'Расчеты с персоналом по оплате труда', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('71', 'Расчеты с подотчетными лицами', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('73', 'Расчеты с персоналом по прочим операциям', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('75', 'Расчеты с учредителями', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('76', 'Расчеты с разными дебиторами и кредиторами', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('77', 'Отложенные налоговые обязательства', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('79', 'Внутрихозяйственные расчеты', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('80', 'Уставный капитал', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('81', 'Собственные акции (доли)', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('82', 'Резервный капитал', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('83', 'Добавочный капитал', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('84', 'Нераспределенная прибыль (непокрытый убыток)', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('86', 'Целевое финансирование', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('90', 'Продажи', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('91', 'Прочие доходы и расходы', '');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('94', 'Недостачи и потери от порчи ценностей', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('96', 'Резервы предстоящих расходов', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('97', 'Расходы будущих периодов', 'А');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('98', 'Доходы будущих периодов', 'П');
INSERT INTO Accounts (`Счет`, `Наименование`, `АП`) VALUES ('99', 'Прибыли и убытки', '');
// Создание таблицы проводок
DROP TABLE IF EXISTS Entries;
CREATE TABLE Entries (`Дата` DATE NOT NULL, `Дебет` VARCHAR(10) NOT NULL, `Кредит` VARCHAR(10) NOT NULL, `Сумма` DECIMAL(12,2) NOT NULL DEFAULT '0', `Содержание` VARCHAR(255) NOT NULL, `Количество` INT NOT NULL, `Дата_Время` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `Номер` MEDIUMINT AUTO_INCREMENT PRIMARY KEY, INDEX (`Дата`));
// Создание таблицы остатков
DROP TABLE IF EXISTS Balances;
CREATE TABLE Balances (`Дата` DATE NOT NULL, `Счет` VARCHAR(10) NOT NULL, `Остаток` DECIMAL(13,2) NOT NULL, `Количество` INT NOT NULL, INDEX (`Дата`,`Счет`));
// Создание таблицы для приходной накладной
DROP TABLE IF EXISTS Invoice;
CREATE TABLE Invoice (`Номер` MEDIUMINT AUTO_INCREMENT PRIMARY KEY, `Дата` DATE NOT NULL, `Товар` VARCHAR(10) NOT NULL, `Кредит` VARCHAR(10) NOT NULL, `Наименование` VARCHAR(63) NOT NULL, `Код` VARCHAR(20) NOT NULL, `Количество` INT NOT NULL, `Сумма` DECIMAL(12,2) NOT NULL DEFAULT '0', `Цена_Розн` DECIMAL(12,2) NOT NULL);
// Создание таблицы шаблонов проводок
DROP TABLE IF EXISTS Stencil;
CREATE TABLE Stencil (`Дебет` VARCHAR(10) NOT NULL, `Кредит` VARCHAR(10) NOT NULL, `Сумма` DECIMAL(12,2) NOT NULL DEFAULT '0', `Содержание` VARCHAR(255) NOT NULL, `Номер` MEDIUMINT AUTO_INCREMENT PRIMARY KEY);
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('20', '10' ,'Списание материала в производство');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('20', '51' ,'Производственный насход');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('26', '51' ,'Комиссия банка');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('26', '51' ,'Уплачены взносы на ОПС (ОМС)');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('26', '60' ,'Получена и списана в расходы услуга');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('26', '62' ,'Комиссия банка по операции эквайринга');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('41', '20' ,'Готовая продукция');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('51', '62' ,'Зачисление от Яндекс по операциям за {Дата-1}. Общая сумма {Сумма/0.965}, комиссия {Сумма/27.57142857}');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('51', '62' ,'Оплата покупателем');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('51', '75' ,'Внесение собственных средств на расчетный счет');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('60', '51' ,'Оплата поставщику за товар, в т.ч. НДС {Сумма/6.55555555}');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('68', '51' ,'Уплачен налог УСН за период');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('75', '51' ,'Перевод на карту (снятие наличных)');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('90', '99' ,'Результаты продаж за период списаны на прибыль');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('99', '26' ,'Расходы за период списаны на прибыль');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('99', '51' ,'Вывод результата предпринимательской деятельности');
INSERT INTO Stencil (`Дебет`, `Кредит`, `Содержание`) VALUES ('99', '68' ,'Начислен налог УСН за период');
// Создание таблицы для загрузки выписки банка
DROP TABLE IF EXISTS LoadBank;
CREATE TABLE LoadBank (`Номер` MEDIUMINT AUTO_INCREMENT PRIMARY KEY, `Дата` DATE NOT NULL, `Дебет` VARCHAR(10) NOT NULL, `Кредит` VARCHAR(10) NOT NULL, `Сумма` DECIMAL(12,2) NOT NULL DEFAULT '0', `НазначениеПлатежа` VARCHAR(255) NOT NULL, `Содержание` VARCHAR(255) NOT NULL, `НомерДок` VARCHAR(12) NOT NULL);
//EXTENDED
